# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# OutsideValleyBottom.py
# Created on: 2015-08-17 16:05:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Created by: Jean M. Olson, South Fork Research, Inc.
# Description: Determines where flowlines fall outside of the Valley Bottom polygon.
#  Adds a field called "InVB" which contains either a "Yes" or a blank.  Segments with
#  blanks fall outside of the Valley Bottom and are selected in a final output file.
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo

# Import arcpy module
import arcpy

# Script arguments
# Input data

Input_Network = arcpy.GetParameterAsText(0)
Input_VB = arcpy.GetParameterAsText(1)
Workspace = arcpy.GetParameterAsText(2)
Scratch = arcpy.GetParameterAsText(3)
Output_Network = arcpy.GetParameterAsText(4)

def main(Input_Network,Input_VB,Workspace,Scratch,Output_Network):

    # Set the workspace environment
    arcpy.env.overwriteOutput = True
    arcpy.env.outputZFlag = "Disabled"
    arcpy.env.workspace = Workspace

    # Local variables:
    WithinVB = Scratch + "\\WithinVB"
    WithinVB_Diss = Scratch + "\\WithinVB_Diss"
    WithinVB_EndPts = Scratch + "\\WithinVB_Diss_EndPts"
    WithinVB_SplitLines = Scratch + "\\WithinVB_SplitLines"
    WithinVB_CntPts = Scratch + "\\WithinVB_CntrPts"
    WithinVB_Join = Scratch + "\\WithinVB_Join"
    WithinVB_SplitJoin = Scratch + "\\WithinVB_SplitJoin"

    #FlowInside_VB = "C:\\GIS\\GIS_Projects\\RiverStyles\\GNAT_Flowlines\\Yankee_Fork\\YF_FlowInside_VB.shp"

    # Process: Intersect:  Intersects the input stream network with the input valley bottom polygon to create stream network
    #     which is fully witin the valley bottom.
    arcpy.Intersect_analysis([Input_Network, Input_VB], WithinVB, "ALL", "", "LINE")

    # Process: Dissolve: Dissolves the joined stream network and valley bottom by GNIS_ID and GNIS_Name
    arcpy.Dissolve_management(WithinVB, WithinVB_Diss, "GNIS_ID;GNIS_Name", "", "SINGLE_PART", "DISSOLVE_LINES")

    # Process: Add Field: Adds a field "InVB" to dissolved feature class 
    arcpy.AddField_management(WithinVB_Diss, "InVB", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

    # Process: Calculate Field: Adds "Yes" to InVB feature class.
    arcpy.CalculateField_management(WithinVB_Diss, "InVB", "\"Yes\"", "VB", "")

    # Process: Feature Vertices To Points: Creates feature class of end points for stream network
    arcpy.FeatureVerticesToPoints_management(WithinVB_Diss, WithinVB_EndPts, "BOTH_ENDS")

    # Process: Split Line at Point: Splits the original stream network by the points of the network inside the valley bottom
    arcpy.SplitLineAtPoint_management(Input_Network, WithinVB_EndPts, WithinVB_SplitLines, "1 Meters")

    # Process: Feature Vertices To Points: Create a point feature class with a point in the center of all segments.
    arcpy.FeatureVerticesToPoints_management(WithinVB_SplitLines, WithinVB_CntPts, "MID")

    # Process: Spatial Join:  Join the center point feature classes to the dissolved stream network
    arcpy.SpatialJoin_analysis(WithinVB_CntPts, WithinVB_Diss, WithinVB_Join, "JOIN_ONE_TO_ONE", "KEEP_ALL",
                               "OBJECTID \"OBJECTID\" true true false 4 Long 0 0 ,First,#," + WithinVB_CntPts + ",OBJECTID,-1,-1;"
                               "Permanent_ \"Permanent_\" true true false 40 Text 0 0 ,First,#," + WithinVB_CntPts + ",Permanent_,-1,-1;"
                               "FDate \"FDate\" true true false 8 Date 0 0 ,First,#," + WithinVB_CntPts + ",FDate,-1,-1;"
                               "Resolution \"Resolution\" true true false 4 Long 0 0 ,First,#," + WithinVB_CntPts + ",Resolution,-1,-1;"
                               "GNIS_ID \"GNIS_ID\" true true false 10 Text 0 0 ,First,#," + WithinVB_CntPts + ", GNIS_ID,-1,-1;"
                               "GNIS_Name \"GNIS_Name\" true true false 65 Text 0 0 ,First,#," + WithinVB_CntPts + ",GNIS_Name,-1,-1;"
                               "ReachCode \"ReachCode\" true true false 14 Text 0 0 ,First,#," + WithinVB_CntPts + ",ReachCode,-1,-1;"
                               "FType \"FType\" true true false 4 Long 0 0 ,First,#," + WithinVB_CntPts + ",FType,-1,-1;"
                               "FCode \"FCode\" true true false 4 Long 0 0 ,First,#," + WithinVB_CntPts + ",FCode,-1,-1;"
                               "Shape_Leng \"Shape_Leng\" true true false 8 Double 0 0 ,First,#," + WithinVB_CntPts + ",Shape_Leng,-1,-1;"
                               "LengthKM \"LengthKM\" true true false 8 Double 0 0 ,First,#," + WithinVB_CntPts + ",LengthKM,-1,-1;"
                               "FlowDir \"FlowDir\" true true false 4 Long 0 0 ,First,#," + WithinVB_CntPts + ",FlowDir,-1,-1;"
                               "WBArea_Per \"WBArea_Per\" true true false 40 Text 0 0 ,First,#," + WithinVB_CntPts + ",WBArea_Per,-1,-1;"
                               "Enabled \"Enabled\" true true false 2 Short 0 0 ,First,#," + WithinVB_CntPts + ",Enabled,-1,-1;"
                               "IsBraided \"IsBraided\" true true false 2 Short 0 0 ,First,#," + WithinVB_CntPts + ",IsBraided,-1,-1;"
                               "IsCon \"IsCon\" true true false 2 Short 0 0 ,First,#," + WithinVB_CntPts + ",IsCon,-1,-1;"
                               "HydroNotes \"HydroNotes\" true true false 100 Text 0 0 ,First,#," + WithinVB_CntPts + ",HydroNotes,-1,-1;"
                               "Shape_Le_1 \"Shape_Le_1\" true true true 8 Double 0 0 ,First,#," + WithinVB_CntPts + ",Shape_Le_1,-1,-1;"
                               "ORIG_FID \"ORIG_FID\" true true false 0 Long 0 0 ,First,#," + WithinVB_CntPts + ",ORIG_FID,-1,-1;"
                               "GNIS_ID_1 \"GNIS_ID_1\" true true false 10 Text 0 0 ,First,#," + WithinVB_Diss + ",GNIS_ID,-1,-1;"
                               "GNIS_Nam_1 \"GNIS_Nam_1\" true true false 65 Text 0 0 ,First,#," + WithinVB_Diss + ",GNIS_Name,-1,-1;"
                               "InVB \"InVB\" true true false 10 Text 0 0 ,First,#," + WithinVB_Diss + ",InVB,-1,-1",
                               "INTERSECT", "", "")

    # Process: Delete Field:  Delete unneeded fields from the join file.
    arcpy.DeleteField_management(WithinVB_Join, "Join_Count;TARGET_FID;OBJECTID;Permanent_;FDate;Resolution;ReachCode;FType;FCode;Shape_Leng;"\
                                 "LengthKM;FlowDir;WBArea_Per;Enabled;IsBraided;IsCon;HydroNotes;ORIG_FID;GNIS_ID_1;GNIS_Nam_1;Permanent1;FDate_1;"\
                                 "Resoluti_1;GNIS_ID_12;GNIS_Nam_2;ReachCod_1;FType_1;FCode_1;Shape_Le_2;LengthKM_1;FlowDir_1;WBArea_P_1;Enabled_1;"\
                                 "IsBraide_1;IsCon_1;HydroNot_1;Shape_Le_3;ORIG_FID_1;Shape_Le_1")

    # Process: Spatial Join: Join the split line file with the previous join file.
    arcpy.SpatialJoin_analysis(WithinVB_SplitLines, WithinVB_Join, WithinVB_SplitJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL",
                               "OBJECTID \"OBJECTID\" true true false 9 Long 0 9 ,First,#," + WithinVB_SplitLines + ",OBJECTID,-1,-1;"
                               "Permanent_ \"Permanent_\" true true false 40 Text 0 0 ,First,#," + WithinVB_SplitLines + ",Permanent_,-1,-1;"
                               "FDate \"FDate\" true true false 8 Date 0 0 ,First,#," + WithinVB_SplitLines + ",FDate,-1,-1;"
                               "Resolution \"Resolution\" true true false 9 Long 0 9 ,First,#," + WithinVB_SplitLines + ",Resolution,-1,-1;"
                               "GNIS_ID \"GNIS_ID\" true true false 10 Text 0 0 ,First,#," + WithinVB_SplitLines + ",GNIS_ID,-1,-1;"
                               "GNIS_Name \"GNIS_Name\" true true false 65 Text 0 0 ,First,#," + WithinVB_SplitLines + ",GNIS_Name,-1,-1;"
                               "ReachCode \"ReachCode\" true true false 14 Text 0 0 ,First,#," + WithinVB_SplitLines + ",ReachCode,-1,-1;"
                               "FType \"FType\" true true false 9 Long 0 9 ,First,#," + WithinVB_SplitLines + ",FType,-1,-1;"
                               "FCode \"FCode\" true true false 9 Long 0 9 ,First,#," + WithinVB_SplitLines + ",FCode,-1,-1;"
                               "Shape_Leng \"Shape_Leng\" true true false 19 Double 0 0 ,First,#," + WithinVB_SplitLines + ",Shape_Leng,-1,-1;"
                               "LengthKM \"LengthKM\" true true false 19 Double 0 0 ,First,#," + WithinVB_SplitLines + ",LengthKM,-1,-1;"
                               "FlowDir \"FlowDir\" true true false 9 Long 0 9 ,First,#," + WithinVB_SplitLines + ",FlowDir,-1,-1;"
                               "WBArea_Per \"WBArea_Per\" true true false 40 Text 0 0 ,First,#," + WithinVB_SplitLines + ",WBArea_Per,-1,-1;"
                               "Enabled \"Enabled\" true true false 4 Short 0 4 ,First,#," + WithinVB_SplitLines + ",Enabled,-1,-1;"
                               "IsBraided \"IsBraided\" true true false 4 Short 0 4 ,First,#," + WithinVB_SplitLines + ",IsBraided,-1,-1;"
                               "IsCon \"IsCon\" true true false 4 Short 0 4 ,First,#," + WithinVB_SplitLines + ",IsCon,-1,-1;"
                               "HydroNotes \"HydroNotes\" true true false 100 Text 0 0 ,First,#," + WithinVB_SplitLines + ",HydroNotes,-1,-1;"
                               "Shape_Le_1 \"Shape_Le_1\" true true false 19 Double 0 0 ,First,#," + WithinVB_SplitLines + ",Shape_Le_1,-1,-1;"
                               "OBJECTID_1 \"OBJECTID\" true true false 4 Long 0 0 ,First,#," + WithinVB_SplitLines + ",OBJECTID,-1,-1;"
                               "Permanent1 \"Permanent_\" true true false 40 Text 0 0 ,First,#," + WithinVB_SplitLines + ",Permanent_,-1,-1;"
                               "FDate_1 \"FDate\" true true false 8 Date 0 0 ,First,#," + WithinVB_SplitLines + ",FDate,-1,-1;"
                               "Resoluti_1 \"Resolution\" true true false 4 Long 0 0 ,First,#," + WithinVB_SplitLines + ",Resolution,-1,-1;"
                               "GNIS_ID_1 \"GNIS_ID\" true true false 10 Text 0 0 ,First,#," + WithinVB_SplitLines + ",GNIS_ID,-1,-1;"
                               "GNIS_Nam_1 \"GNIS_Name\" true true false 65 Text 0 0 ,First,#," + WithinVB_SplitLines + ",GNIS_Name,-1,-1;"
                               "ReachCod_1 \"ReachCode\" true true false 14 Text 0 0 ,First,#," + WithinVB_SplitLines + ",ReachCode,-1,-1;"
                               "FType_1 \"FType\" true true false 4 Long 0 0 ,First,#," + WithinVB_SplitLines + ",FType,-1,-1;"
                               "FCode_1 \"FCode\" true true false 4 Long 0 0 ,First,#," + WithinVB_SplitLines + ",FCode,-1,-1;"
                               "Shape_Le_2 \"Shape_Leng\" true true false 8 Double 0 0 ,First,#," + WithinVB_SplitLines + ",Shape_Leng,-1,-1;"
                               "LengthKM_1 \"LengthKM\" true true false 8 Double 0 0 ,First,#," + WithinVB_SplitLines + ",LengthKM,-1,-1;"
                               "FlowDir_1 \"FlowDir\" true true false 4 Long 0 0 ,First,#," + WithinVB_SplitLines + ",FlowDir,-1,-1;"
                               "WBArea_P_1 \"WBArea_Per\" true true false 40 Text 0 0 ,First,#," + WithinVB_SplitLines + ",WBArea_Per,-1,-1;"
                               "Enabled_1 \"Enabled\" true true false 2 Short 0 0 ,First,#," + WithinVB_SplitLines + ",Enabled,-1,-1;"
                              "IsBraide_1 \"IsBraided\" true true false 2 Short 0 0 ,First,#," + WithinVB_SplitLines + ",IsBraided,-1,-1;"
                               "IsCon_1 \"IsCon\" true true false 2 Short 0 0 ,First,#," + WithinVB_SplitLines + ",IsCon,-1,-1;"
                               "HydroNot_1 \"HydroNotes\" true true false 100 Text 0 0 ,First,#," + WithinVB_SplitLines + ",HydroNotes,-1,-1;"
                               "Shape_Le_3 \"Shape_Le_3\" true true true 8 Double 0 0 ,First,#," + WithinVB_SplitLines + ",Shape_Le_1,-1,-1;"
                               "GNIS_ID_12 \"GNIS_ID\" true true false 10 Text 0 0 ,First,#," + WithinVB_Join + ",GNIS_ID,-1,-1;"
                               "GNIS_Nam_2 \"GNIS_Name\" true true false 65 Text 0 0 ,First,#," + WithinVB_Join + ",GNIS_Name,-1,-1;"
                               "Shape_Le_4 \"Shape_Le_4\" true true true 8 Double 0 0 ,First,#," + WithinVB_Join + ",Shape_Le_1,-1,-1;"
                               "InVB \"InVB\" true true false 10 Text 0 0 ,First,#," + WithinVB_Join + ",InVB,-1,-1",
                               "INTERSECT", "", "")

    # Process: Delete Field: Delete unneeded fields from the join file.
    arcpy.DeleteField_management(WithinVB_SplitJoin, "Join_Count;TARGET_FID;Shape_Le_1;Permanent1;FDate_1;Resoluti_1;GNIS_ID_1;GNIS_Nam_1;ReachCod_1;"\
                                 "FType_1;FCode_1;Shape_Le_2;LengthKM_1;FlowDir_1;WBArea_P_1;Enabled_1;IsBraide_1;IsCon_1;HydroNot_1;GNIS_ID_12;GNIS_Nam_2;"\
                                 "Shape_Le_3;Shape_Le_4;OBJECTID")


    # Select: Select the features that fall outside Valley Bottom and create output feature class.
    arcpy.Select_analysis(WithinVB_SplitJoin, Output_Network,""""InVB" IS NULL""")
